service: auth-backend

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: home
  versionFunctions: false
  logRetentionInDays: 30
  environment:
    AUTH_TABLE: ${self:custom.authTableName}
    SECRET_JWT_HASH: ${ssm:/penny/${self:custom.stage}/auth/secretKey}
  deploymentBucket:
    name: serverless-deployment.pennybusproject.com
custom:
  stage: ${opt:stage, self:provider.stage}
  environments:
    dev: dev
    prod: prod
  environment: ${self:custom.environments.${self:custom.stage}, self:custom.environments.dev}
  authTableName: ${ssm:/global/${self:custom.stage}/dynamo/AuthTable/name}
  authTableARN: ${ssm:/global/${self:custom.stage}/dynamo/AuthTable/arn}
  esbuild:
    bundle: true
    minify: false
    packagePath: package.json
    external:
      - bcryot

plugins:
  - serverless-esbuild
  - serverless-offline
functions:
  Create:
    handler: ./Create.handler
    role: CreateAuthTableLambdaRole
    events:
      - http:
          method: POST
          path: auth/create

  Login:
    handler: Login.handler
    role: ReadAuthTableLambdaRole
    events:
      - http:
          method: POST
          path: auth/login

  Refresh:
    handler: Refresh.handler
    role: CreateAuthTableLambdaRole
    events:
      - http:
          method: POST
          path: auth/refresh

  Authenticate:
    handler: Authenticate.handler
    role: ReadAuthTableLambdaRole
    events:
      - http:
          method: POST
          path: auth/authenticate

resources:
  Resources:
    CreateAuthTableLambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: CreateAuthTableLambdaRole-${self:custom.stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: "LambdaRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - logs:*
                  Resource: arn:aws:logs:*:*:*

          - PolicyName: "CreateAuthDBPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:PutItem"
                    - "dynamodb:UpdateItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:BatchGetItem"
                    - "dynamodb:Scan"
                    - "dynamodb:Query"
                    - "dynamodb:ConditionCheckItem"
                  Resource:
                    - "${self:custom.authTableARN}"
                    - "${self:custom.authTableARN}/index/*"

    ReadAuthTableLambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: ReadAuthTableLambdaRole-${self:custom.stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: "LambdaRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - logs:*
                  Resource: arn:aws:logs:*:*:*

          - PolicyName: "ReadAuthDBPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:GetItem"
                  Resource: ${self:custom.authTableARN}

    DeleteAuthTableLambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: DeleteAuthTableLambdaRole-${self:custom.stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: "LambdaRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - logs:*
                  Resource: arn:aws:logs:*:*:*

          - PolicyName: "DeleteAuthDBPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:DeleteItem"
                  Resource: ${self:custom.authTableARN}
  Outputs:
    PennyAuthAPI:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ExtPennyAuthAPI-${self:custom.stage}
