service: table-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: home
  versionFunctions: false
  logRetentionInDays: 30

custom:
  stage: ${opt:stage, self:provider.stage}
  deletionPolicies: #dynamoDB deletion policy
    dev: Retain
    prod: Retain
  deletionPolicy: ${self:custom.deletionPolicies.${self:custom.stage}, 'Delete'}

resources:
  Resources:
    PennyTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: ${self:custom.deletionPolicy}
      Properties:
        TableName: Penny-${self:custom.stage}
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

        # StreamSpecification:
        #   StreamViewType: NEW_AND_OLD_IMAGES
    PennyTableName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /penny/${self:custom.stage}/dynamo/PennyTable/name
        Type: String
        Value: !Ref PennyTable

    PennyTableArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /penny/${self:custom.stage}/dynamo/PennyTable/arn
        Type: String
        Value: !GetAtt PennyTable.Arn

    # PennyTableStreamArn:
    #   Type: AWS::SSM::Parameter
    #   Properties:
    #     Name: /penny/${self:custom.stage}/dynamo/relationTable/streamArn
    #     Type: String
    #     Value: !GetAtt PennyTable.StreamArn


    AuthTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: ${self:custom.deletionPolicy}
      Properties:
        TableName: Auth-${self:custom.stage}
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        # StreamSpecification:
        #   StreamViewType: NEW_AND_OLD_IMAGES

    AuthTableName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /global/${self:custom.stage}/dynamo/AuthTable/name
        Type: String
        Value: !Ref AuthTable

    AuthTableArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /global/${self:custom.stage}/dynamo/AuthTable/arn
        Type: String
        Value: !GetAtt AuthTable.Arn
    # PennyTableStreamArn:
    #   Type: AWS::SSM::Parameter
    #   Properties:
    #     Name: /penny/${self:custom.stage}/dynamo/relationTable/streamArn
    #     Type: String
    #     Value: !GetAtt PennyTable.StreamArn
